AWSTemplateFormatVersion: '2010-09-09'
Description: 'DynamoDB storage for Werewolf'

Parameters:
    TableName:
        Type: String
        Default: 'WEREWOLF-Games'

Resources:
    WerewolfTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: !Ref TableName
            AttributeDefinitions:
                - AttributeName: Id
                  AttributeType: S
            KeySchema:
                - AttributeName: Id
                  KeyType: HASH
            BillingMode: PAY_PER_REQUEST
            SSESpecification:
                SSEEnabled: true

Outputs:
    TableName:
        Description: 'DynamoDB table storing all Werewolf games'
        Value: !Ref WerewolfTable
